[package]
name = "proxy-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proxy-rs"
path = "src/proxy.rs"

[dependencies]
chrono = "0.4"
chrono-tz = "0.10"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"]}
toml = "1"
tokio = {version = "1", features = ["full"]}
