[package]
name = "proxy-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proxy-rs"
path = "proxy.rs"

[dependencies]
chrono = "0.4"
chrono-tz = "0.10"
dotenvy = "0.15"
tokio = {version = "1", features = ["full"]}
